apiVersion: v1 
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: app
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
---
apiVersion: v1 
kind: Secret
metadata:
  name: payment
  namespace: roboshop
  labels: 
    project: roboshop
    component: payment
    tier: app
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:  
      project: roboshop
      component: payment
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        component: payment
        tier: app
    spec:
      containers:
      - name: payment
        image: maheswari450/payment-optimise:v1
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: payment
        - secretRef:
            name: payment
---
apiVersion: v1 
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    component: payment
    tier: app
spec:
  selector:
    project: roboshop
    component: payment
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 10