apiVersion: v1 
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: app
data:
  CART_ENDPOINT: "cart:8080" 
  DB_HOST: "mysql" 
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:  
      project: roboshop
      component: shipping
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: app
    spec:
      containers:
      - name: shipping
        image: maheswari450/shipping-optimise:v1
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1 
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: app
spec:
  selector:
    project: roboshop
    component: shipping
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource 
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10