apiVersion : v1 
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: DB 
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3A=
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: DB 
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: rabbitmq
    tier: DB 
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: DB 
spec:
  selector:
    project: roboshop
    component: rabbitmq
    tier: DB 
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: DB 
spec:
  replicas: 2
  serviceName: "rabbitmq-headless"
  selector:
    matchLabels:
      project: roboshop
      component: rabbitmq
      tier: DB 
  template:
    metadata:
      labels:
        project: roboshop
        component: rabbitmq
        tier: DB 
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - secretRef:
            name: rabbitmq
        volumeMounts:
        - name: rabbitmq-data-pvc
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-sc
      resources:
        requests:
          storage: 2Gi