apiVersion : v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: DB
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: mongodb
    tier: DB
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion : v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: DB
spec:
  selector:
    project: roboshop
    component: mongodb
    tier: DB
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: DB
spec:
  replicas: 3
  serviceName: "mongodb-headless" # this should be headless service
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: DB
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: DB
    spec:
      containers:
      - name: mongodb
        image: maheswari450/mongodb-optimise:v1
        volumeMounts:
        - name: monogdb-data-pvc
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: monogdb-data-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-sc
      resources:
        requests:
          storage: 2Gi