apiVersion: v1 
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: app
data:
  REDIS_URL: 'redis://redis:6379' 
  MONGO_URL: "mongodb://mongodb:27017/users"
  MONGO: "true"
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:  
      project: roboshop
      component: user
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        component: user
        tier: app
    spec:
      containers:
      - name: user
        image: maheswari450/user-optimise:v1
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1 
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: app
spec:
  selector:
    project: roboshop
    component: user
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
--- 
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource 
    resource:
      name: cpu
      target: 
        type: Utilization
        averageUtilization: 10